### ISSUE TITLE
Filtering events before dumping them on stdout of the exporter

### ISSUE THREAD

**Issue by sivarama-p-raju** [kubesphere/kube-events#169]
Could someone please let me know if there is a possibility of filtering events and dropping specific events before the rest of the events are dumped on stdout of the exporter ?

For example, I would like to drop all events with reason equals "PolicyApplied" as there are tons of these events and I would like to avoid on the stdout.

I am not sure if a rule can be created at a cluster scope level to achieve this ?

Below might be an example:
```
apiVersion: events.kubesphere.io/v1alpha1
kind: Rule
metadata:
  labels:
    kubesphere.io/rule-scope: cluster
  name: drop-specific-events
  namespace: test
spec:
  rules:
  - condition: |
      reason == "PolicyApplied"
    enable: true
    name: DropPolicyApplied
    type: drop
```

I have tried Kubernetes event exporter (resmoio/kubernetes-event-exporter) as well, and there are possibilities of dropping specific events before dumping the rest of the events to a receiver (stdout for example). However, there are some challenges with that as I was unable to figure out a way to drop events with specific name (using wildcards) and also to print the last timestamp of the event.

"kubesphere/kube-events" prints the last timestamp, which is exactly what I wanted. The only thing I need help with is to identify a way to filter the events by dropping specific events with reason, or name etc.

Thanks a lot in advance.
