### ISSUE TITLE
kube-evnets Ruler bug

### ISSUE THREAD

**Issue by Shuimo03** [kubesphere/kube-events#43]
```yaml
apiVersion: events.kubesphere.io/v1alpha1
kind: Ruler
metadata:
  name: kube-events-alertmanager-ruler
  namespace: kubesphere-logging-system
spec:
  image: kubesphere/kube-events-ruler:0.5.0
  replicas: 1
  resources: {}
  ruleNamespaceSelector: {}
  ruleSelector: {}
  sinks:
    alertmanagers
      name: alertmanager-main
      namespace: monitoring
      port: 9093
      targetPort: 9093
```

The request is invalid: patch: Invalid value: "{\"apiVersion\":\"events.kubesphere.io/v1alpha1\",\"kind\":\"Ruler\",\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"events.kubesphere.io/v1alpha1\\\",\\\"kind\\\":\\\"Ruler\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"kube-events-alertmanager-ruler\\\",\\\"namespace\\\":\\\"kubesphere-logging-system\\\"},\\\"spec\\\":{\\\"image\\\":\\\"kubesphere/kube-events-ruler:0.5.0\\\",\\\"replicas\\\":1,\\\"resources\\\":{},\\\"ruleNamespaceSelector\\\":{},\\\"ruleSelector\\\":{},\\\"sinks\\\":{\\\"alertmanagers\\\":{\\\"name\\\":\\\"alertmanager-main\\\",\\\"namespace\\\":\\\"monitoring\\\",\\\"port\\\":9093,\\\"targetPort\\\":9093}}}}\\n\"},\"creationTimestamp\":\"2023-02-07T08:43:21Z\",\"finalizers\":[\"rulers.finalizer.events.kubesphere.io\"],\"generation\":2,\"managedFields\":[{\"apiVersion\":\"events.kubesphere.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:finalizers\":{\".\":{},\"v:\\\"rulers.finalizer.events.kubesphere.io\\\"\":{}}},\"f:status\":{}},\"manager\":\"kube-events-operator\",\"operation\":\"Update\",\"time\":\"2023-02-07T08:43:21Z\"},{\"apiVersion\":\"events.kubesphere.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kubectl.kubernetes.io/last-applied-configuration\":{}}},\"f:spec\":{\".\":{},\"f:image\":{},\"f:replicas\":{},\"f:resources\":{},\"f:ruleNamespaceSelector\":{},\"f:ruleSelector\":{},\"f:sinks\":{\".\":{},\"f:alertmanager\":{\".\":{},\"f:name\":{},\"f:namespace\":{}}}}},\"manager\":\"kubectl-client-side-apply\",\"operation\":\"Update\",\"time\":\"2023-02-07T08:43:21Z\"}],\"name\":\"kube-events-alertmanager-ruler\",\"namespace\":\"kubesphere-logging-system\",\"resourceVersion\":\"335279\",\"uid\":\"03a085b5-25a7-4860-ac19-7d311c8525fd\"},\"spec\":{\"image\":\"kubesphere/kube-events-ruler:0.5.0\",\"replicas\":1,\"resources\":{},\"ruleNamespaceSelector\":{},\"ruleSelector\":{},\"sinks\":{\"alertmanagers\":{\"name\":\"alertmanager-main\",\"namespace\":\"monitoring\",\"port\":9093,\"targetPort\":9093}}},\"status\":{}}": strict decoding error: unknown field "spec.sinks.alertmanagers.name", unknown field "spec.sinks.alertmanagers.namespace", unknown field "spec.sinks.alertmanagers.port", unknown field "spec.sinks.alertmanagers.targetPort"
