### ISSUE TITLE
exporter 404 and ruler sinks alert manager

### ISSUE THREAD

**Issue by Shuimo03** [kubesphere/kube-events#44]
When I created the ruler about alertmanager sinks, I intentionally filled in some wrong information, but the ruler-alertmanager-pod logs still show rule cache succeeded,Here is my ruler.yaml
```yaml
apiVersion: events.kubesphere.io/v1alpha1
kind: Ruler
metadata:
  name: kube-events-alertmanager-ruler
  namespace: kubesphere-logging-system
spec:
  image: kubesphere/kube-events-ruler:0.5.0
  replicas: 1
  resources: {} #985
  ruleNamespaceSelector: {} #1012
  ruleSelector: {}
  sinks:
    alertmanagers: 
      - namespace: monitoring
        name: alertmanager-main
        port: 9093
        targetPort: 9093
```
And my exporter component prompts a 404 when using the k8s service, but the url doesn't.
``` yaml
apiVersion: events.kubesphere.io/v1alpha1
kind: Exporter
metadata:
  name: kube-events-exporter
  namespace: kubesphere-logging-system
spec:
  image: kubesphere/kube-events-exporter:0.5.0
  resources: {}
  sinks:
    stdout: {}
    webhooks:
          name: kube-events-alertmanager-ruler
         namespace: kubesphere-logging-system
          path: events/meteics
          port: 8443
```

K8S is minikube, version is  v1.25.3
CNI: cilium
